### ISSUE TITLE
Find a better name for `dm`

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/matterhorn#28]
Such as `msg`.  I'd suggest adding command aliases but in this case I think (say) `msg` is a better name and is going to be less surprising.

**Comment by dagit** [comment]
My thoughts:

  * When `/msg` command appears in chat clients it's typically for messaging a user (not just focusing on a chat window)
  * We could design the command so that it takes an optional message
  * Internally we know the difference between users and channels. We could have a unified /-command that works as long as the channel or nickname is unambiguous. In the ambiguous case we would tell the user to use `@` or `#` to differentiate. I'm assuming #27 gets fixed.

So it could be something like:

`/msg (channel|username) [message]` where `[message]` means it's optional.

I think I'd rather have two commands:

  * `/msg (channel|username) message` -> sends a message to the channel or user without changing the focus in the UI
  * `/window (channel|username)` -> changes the focus in the UI but doesn't send a message. I'm not tied to the verb choice here, `/window` is just an example. Other things could be equally effective.

**Comment by jtdaugherty** [comment]
I like the two-command approach you proposed.

**Comment by jtdaugherty** [comment]
Maybe `/focus` would be better than `/window` since we don't really have a notion of "window"?

**Comment by jtdaugherty** [comment]
(So, `/msg` and `/focus`.)

**Comment by jtdaugherty** [comment]
Right now, since we forward unrecognized commands to the server, we actually get `/msg` for free. If you message someone in this way in Matterhorn, it does what you expect even though `/msg` doesn't appear in our help output (since it is not a client command). I think this is kinda nice but is confusing. Instead of sending all unrecognized commands to the server, I'd rather whitelist them and add them to our `/help` output.

**Comment by aisamanra** [comment]
Closed. WONTFIX. We accept pull requests in JIRA.

(Or, well, we don't actually have `dm` any more, and Jason and I both contend that the focus commands we have are fine.)
