### ISSUE TITLE
Make unread direct messages easier to spot

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/matterhorn#36]
Right now the direct message channel (user) list is long enough that you have to scroll it just to check on whether there are any unread messages.  To make it easier to tell if there are unread messages (but to preserve the ability to message anyone by scrolling to their name), I propose we sort the user list by most recent communication.  This could be annoying but it's also optimized for the common case by showing you users with whom you communicated most recently.  And if we have a good `/focus` command then it's no longer important to sort the list alphabetically.

Thoughts @dagit and @aisamanra?

**Comment by jtdaugherty** [comment]
(Put another way: I want to get away from making scrolling the most useful means of navigating the list.)

**Comment by dagit** [comment]
I also wanted to experiment with separating out channels that have unread messages and floating them to the top as a separate list entirely. I don't know if that's a good idea so I want to try it before committing to it.

Otherwise, what you're proposing sounds good. There are also some keybindings we could implement to help:

  * keybinding to jump to next channel with unread messages (I propose Alt+a)
  * keybinding jump back to most recently focused channel (I propose Alt+s)

**Comment by jtdaugherty** [comment]
Bindings for improved channel navigation sound good to me!

**Comment by dagit** [comment]
Related to this, I changed the indicator for unread messages in a channel (including direct message channels). Now it uses a cyan bg similar to how the focused channel works.

**Comment by dagit** [comment]
Given all the recent UI changes plus the keybindings in 4e94212, I consider this complete. Reopen if you want more.
