### ISSUE TITLE
Display UI immediately ASAP, load data asychronously

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/matterhorn#4]
The client interface takes a few seconds (sometimes 3-5s for me) to appear while various data are fetched.  I'd like to refactor things so that we can go ahead and show the UI with no channels and some status information like "Loading..." rather than staring at the shell wondering what is happening.

**Comment by dagit** [comment]
Does brick or vty have a notion of *off screen rendering*? In graphical libraries you can take your time rendering to an off screen buffer and then when it's ready switch the display to use that buffer. It might be nice to prepare things off screen and then make it active once it's fully loaded. Otherwise, I guess the "Loading..." indicator could be displayed on top of the other widgets.

**Comment by aisamanra** [comment]
Current status: _much_ faster than it was before, but we still load some things (channel list, user list, messages in `town-square`) synchonously. That said, I'm going to leave this issue open, because I think we should probably go further towards making the UI load up.

**Comment by aisamanra** [comment]
Okay, at this point we load chat channels asynchronously on startup and DM channels on-demand, which goes a long way to making this faster. It still takes a half-second, but I think we can consider this closed, unless we want to have the UI pop up _immediately_ before _any_ data has been fetched, which I generally don't think is necessary—the half-second pause seems perfectly okay to me.
