### ISSUE TITLE
Connection health and autoreconnect

### ISSUE THREAD

**Issue by dagit** [aisamanra/matterhorn#7]
I don't see this as a core feature, but instead as a nice to have feature.

We should make an effort to detect when the websocket connection is dead and reconnect as soon as possible. The way [glirc](https://github.com/glguy/irc-core) handles this is to use  a ping + timer. If there is no response from a ping after N seconds (by default N = 60) the client initiates a reconnect.

I  don't know if the websockets library exposes server pings or not. If it does not, then we could simulate it by periodically initiating benign requests such as `mmGetMe` that just test our ability to fetch data that should always be available to us.

It's also worth noting that this connection health could correspond to both the one shot HTTP requests and the websocket connection. It's likely worth monitoring both. If we only test HTTP request we could hit an edge case where the internet connection dropped for just long enough to disrupt the websocket but came back fast enough to not interrupt HTTP requests.

**Comment by benjaminfjones** [comment]
I see this as being more than a "nice to have". For example, if I'm running a client on my laptop and I shut the lid, then open later it appears that I'm still connected to Mattermost, but in fact the connection is broken.

I think at the very least the *connection health* component should be part of the minimum client.

**Comment by jtdaugherty** [comment]
Yeah, I agree. Tag removed.

**Comment by aisamanra** [comment]
This feature is halfway there:
- We detect a ping timeout and visually indicate in the top-right corner that the connection is dead
- We sporadically attempt to reconnect, and after reconnecting you'll see new messages as they come in.

Some features which are currently missing:
- We try to reconnect every five seconds, and we probably should have some kind of backoff over time so that we're not perpetually trying to vainly reconnect when we're not connected to the network
- We don't report the health beyond a binary of _connected_/_not connected_, and it would be nice to report a good/fair/poor connection quality based on the latency.
- Most importantly, we don't fetch any history on reconnection: you'll see messages from before the drop, and from after, but not from the period you weren't connected.

**Comment by jtdaugherty** [comment]
Latest update: we now catch *all* exceptions in the ping management threads to avoid stderr poisoning when those threads crash.  Before, we only caught specific websocket timeout exceptions.

**Comment by jtdaugherty** [comment]
Any other thoughts on what we can do before calling this done?

The only thing I can think of is to make the client check for updates when the websocket comes back up (i.e. refresh all state).

**Comment by dagit** [comment]
Yeah, I think refreshing the state is the next obvious thing. After that I think it makes sense to close this issue.

**Comment by aisamanra** [comment]
As of ead74fb we now refresh messages, but no other state.

**Comment by aisamanra** [comment]
I'm going to close this one and open another issue for refreshing the rest of the state: "refresh user/channel metadata on reconnect" is significantly different enough from this issue's title of "connection health and autoreconnect" that I think it should be recorded elsewhere.
