### ISSUE TITLE
only mark channel seen if user pauses

### ISSUE THREAD

**Issue by dagit** [aisamanra/matterhorn#77]
If you're using C+n/p to cycle through channels, we should probably only mark the channel as read if the users pauses on a channel for a bit (say 2 seconds?). This would make it easier to use the keybindings to move a few channels without "reading" any of the intermediate channels.

**Comment by jtdaugherty** [comment]
I've wondered about this approach, too. I think it's tricky thing because the timeout would have to be chosen carefully so that it never requires you to sit on a channel on purpose long enough to mark it as read (which you won't be able to observe).

This bites me whenever I want to move to a channel that is a few channels away from where I am, with unread messages in between.  It occurred to me that another approach would be to add a shortcut key that lets you start typing a channel name and then hit Enter to switch to the one that matches what you've typed - it's a little hard for me to describe, so perhaps I should hack it up on a branch to show what I mean.  This is part of my thinking about ways to make C-n/C-p either behave better or be completely unnecessary.

**Comment by jtdaugherty** [comment]
(And the approach I described would be nice anyway, irrespective of whether you want to manage unread message states - I just find it annoying to have to type `/focus`.)

**Comment by jtdaugherty** [comment]
Okay, this is now in `master` - try it out!  Workflow:
* Press `C-g`.
* Start typing a channel name or user name.
* Partial matches are shown.
* If a unique match is available, pressing `Enter` will change to that channel.
* Backspace does what you want.
* Esc returns to normal mode.

**Comment by jtdaugherty** [comment]
I want to also make it so you can maybe hit Tab to cycle between candidates, but at least for now that's usually unnecessary because most unique prefixes are short.

**Comment by jtdaugherty** [comment]
Any opinions on whether this can be closed? I'm in favor of closing since I think we side-stepped this issue with the navigation improvements.

**Comment by jtdaugherty** [comment]
I consider this has been addressed well enough that it can be closed.
