### ISSUE TITLE
autoscrolling should be disabled when the user has scrollback

### ISSUE THREAD

**Issue by dagit** [aisamanra/matterhorn#83]
Right now if you press page up a few times to read the scrollback, then when a new message arrives it will automatically scroll to the bottom. This can be annoying if you're in the middle of reading something.

**Comment by jtdaugherty** [comment]
Due to how scrolling works in `brick` (and since we're using brick to drive the scrolling here rather than rolling our own solution), an approach that I can think of for this is to keep track of the number of page-ups the user has done, and when they've done as many page-downs to return to the bottom, then resume normal operations by keeping the list scrolled to the bottom.  In addition, reset the page-up counter on channel switch.

**Comment by jtdaugherty** [comment]
Thinking about this a bit more, this actually won't work because while you are paged up, messages that arrive *increase the number of page-downs you'll have to do to get back to the bottom*.  So we need another approach.

**Comment by jtdaugherty** [comment]
Other approaches:
 * Require a keybinding to get into scrolling mode, so we can also have a way of getting out.
 * Stop using brick for scrolling and roll our own and do all the book-keeping that would be required to tell when it's safe to resume auto-scrolling.

**Comment by jtdaugherty** [comment]
Alternatively I could have brick expose more of its viewport internals. I've so far tried to avoid that, but for cases like this it's really useful to have.
