### ISSUE TITLE
load additional scrollback on page up

### ISSUE THREAD

**Issue by dagit** [aisamanra/matterhorn#91]
We should attempt to fetch additional scrollback when you get to the top of the scrollback.

**Comment by jtdaugherty** [comment]
In looking into how we might do this I've concluded that it's going to be a while before we can redo how we deal with messages and scrolling, so *automatically* loading messages on scrolling is going to have to wait. However! I had an alternative proposal that might be okay and might also work. The proposal is to prepend a message at the top of each channel's message list so that when you do get to the top, you see something like
```
  << Press C-L to load more messages >>
[00:01] bob: foo is great
```
and then the user has to do press this to load more, at which point they could scroll up a bit more. If we could make this work, would that be sufficient?

**Comment by dagit** [comment]
Yeah, that would work for now. Thanks!
>
>
